<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>LevelApp.Instruments.Leveltronic.UI</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWinUI>true</UseWinUI>
    <Version>0.20.0</Version>
    <AssemblyVersion>0.20.0.0</AssemblyVersion>
    <FileVersion>0.20.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.260317003" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.4654" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LevelApp.Core\LevelApp.Core.csproj" />
    <ProjectReference Include="..\LevelApp.Instruments.BLE\LevelApp.Instruments.BLE.csproj" />
    <ProjectReference Include="..\LevelApp.Instruments.UsbHid\LevelApp.Instruments.UsbHid.csproj" />
    <ProjectReference Include="..\LevelApp.Instruments.Leveltronic\LevelApp.Instruments.Leveltronic.csproj" />
  </ItemGroup>

</Project>
